version: '3.7'

services:
  api:
    image: yasuoyuhao/nest-temp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    networks:
     - docker-ts-nest-net
    expose:
     - 3000
    # volumes:
    #  - .:/api
    # depends_on:
    #  - redis
    environment: 
      NODE_ENV: test
  # redis:
  #   image: redis:alpine
  #   networks:
  #    - docker-ts-nest-net

networks:
  docker-ts-nest-net:
    driver: bridge